/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.DoctorLogs;
import Model.PatientLogs;
import Model.PersonLogs;
import Model.User;
import Model.UserLogs;
import javax.swing.JSplitPane;

/**
 *
 * @author arpitabhagat
 */
public class AdminHealthCareOverview extends javax.swing.JPanel {

    /**
     * Creates new form Testlogin
     */
    PersonLogs personLogs;
    UserLogs userLogs;
    JSplitPane jSplitPane1;
    PatientLogs patientLogs;
    DoctorLogs doctorLogs;
    public AdminHealthCareOverview(PersonLogs personLogs,UserLogs userLogs, JSplitPane jSplitPane1,PatientLogs patientLogs,DoctorLogs doctorLogs) {
        initComponents();
        this.personLogs = personLogs;
        this.userLogs = userLogs;
        this.jSplitPane1 = jSplitPane1;
        this.patientLogs = patientLogs;
        this.doctorLogs = doctorLogs;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePerson = new javax.swing.JButton();
        btnCreatePatient = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 255));

        btnCreatePerson.setBackground(new java.awt.Color(0, 0, 0));
        btnCreatePerson.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePerson.setText("CREATE PERSON");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnCreatePatient.setBackground(new java.awt.Color(0, 0, 0));
        btnCreatePatient.setForeground(new java.awt.Color(255, 255, 255));
        btnCreatePatient.setText("CREATE PATIENT");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnCreateDoctor.setBackground(new java.awt.Color(0, 0, 0));
        btnCreateDoctor.setForeground(new java.awt.Color(255, 255, 255));
        btnCreateDoctor.setText("CREATE DOCTOR");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("ADMIN");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreatePatient)
                            .addComponent(btnCreateDoctor)
                            .addComponent(btnCreatePerson)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(439, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(72, 72, 72)
                .addComponent(btnCreatePerson)
                .addGap(35, 35, 35)
                .addComponent(btnCreateDoctor)
                .addGap(32, 32, 32)
                .addComponent(btnCreatePatient)
                .addContainerGap(331, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        AdminCreatePerson cP = new AdminCreatePerson(personLogs,userLogs,jSplitPane1,patientLogs,doctorLogs);
        jSplitPane1.setRightComponent(cP);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        AdminCreatePatient aCP = new AdminCreatePatient(personLogs,userLogs,jSplitPane1,patientLogs,doctorLogs);
        jSplitPane1.setRightComponent(aCP);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        AdminCreateDoctor aCD = new AdminCreateDoctor(personLogs,userLogs,jSplitPane1,patientLogs,doctorLogs);
        jSplitPane1.setRightComponent(aCD);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnCreatePerson;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
