/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.DoctorLogs;
import Model.PatientLogs;
import Model.PersonLogs;
import Model.User;
import Model.UserLogs;
import javax.swing.JSplitPane;

/**
 *
 * @author arpitabhagat
 */
public class AdminHealthCareOverview extends javax.swing.JPanel {

    /**
     * Creates new form Testlogin
     */
    PersonLogs personDirectory;
    UserLogs userDirectory;
    JSplitPane jSplitPane1;
    PatientLogs patientDirectory;
    DoctorLogs doctorDirectory;
    public AdminHealthCareOverview(PersonLogs personDirectory,UserLogs userDirectory, JSplitPane jSplitPane1,PatientLogs patientDirectory,DoctorLogs doctorDirectory) {
        initComponents();
        this.personDirectory = personDirectory;
        this.userDirectory = userDirectory;
        this.jSplitPane1 = jSplitPane1;
        this.patientDirectory = patientDirectory;
        this.doctorDirectory = doctorDirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePerson = new javax.swing.JButton();
        btnCreatePatient = new javax.swing.JButton();
        btnCreateDoctor = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        btnCreatePatient.setText("Create Patient");
        btnCreatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePatientActionPerformed(evt);
            }
        });

        btnCreateDoctor.setText("Create Doctor");
        btnCreateDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateDoctorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnCreatePerson)
                .addGap(62, 62, 62)
                .addComponent(btnCreatePatient)
                .addGap(53, 53, 53)
                .addComponent(btnCreateDoctor)
                .addContainerGap(457, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreatePerson)
                    .addComponent(btnCreatePatient)
                    .addComponent(btnCreateDoctor))
                .addContainerGap(542, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        AdminCreatePerson cP = new AdminCreatePerson(personDirectory,userDirectory,jSplitPane1,patientDirectory,doctorDirectory);
        jSplitPane1.setRightComponent(cP);
    }//GEN-LAST:event_btnCreatePersonActionPerformed

    private void btnCreatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePatientActionPerformed
        // TODO add your handling code here:
        AdminCreatePatient aCP = new AdminCreatePatient(personDirectory,userDirectory,jSplitPane1,patientDirectory,doctorDirectory);
        jSplitPane1.setRightComponent(aCP);
    }//GEN-LAST:event_btnCreatePatientActionPerformed

    private void btnCreateDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateDoctorActionPerformed
        // TODO add your handling code here:
        AdminCreateDoctor aCD = new AdminCreateDoctor(personDirectory,userDirectory,jSplitPane1,patientDirectory,doctorDirectory);
        jSplitPane1.setRightComponent(aCD);
    }//GEN-LAST:event_btnCreateDoctorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateDoctor;
    private javax.swing.JButton btnCreatePatient;
    private javax.swing.JButton btnCreatePerson;
    // End of variables declaration//GEN-END:variables
}
