/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.PersonLogs;
import Model.User;
import Model.UserLogs;
import javax.swing.JSplitPane;

/**
 *
 * @author arpitabhagat
 */
public class HealthCareOverview extends javax.swing.JPanel {

    /**
     * Creates new form Testlogin
     */
    PersonLogs personDirectory;
    UserLogs userDirectory;
   JSplitPane jSplitPane1;
   
    public HealthCareOverview(PersonLogs personDirectory,UserLogs userDirectory, JSplitPane jSplitPane1) {
        initComponents();
        this.personDirectory = personDirectory;
        this.userDirectory = userDirectory;
        this.jSplitPane1 = jSplitPane1; 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreatePerson = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));

        btnCreatePerson.setText("Create Person");
        btnCreatePerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreatePersonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnCreatePerson)
                .addContainerGap(396, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnCreatePerson)
                .addContainerGap(356, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreatePersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreatePersonActionPerformed
        // TODO add your handling code here:
        CreatePerson cP = new CreatePerson(personDirectory,userDirectory,jSplitPane1);
        jSplitPane1.setRightComponent(cP);
        
    }//GEN-LAST:event_btnCreatePersonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreatePerson;
    // End of variables declaration//GEN-END:variables
}
