/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.DoctorLogs;
import Model.EncounterLogs;
import Model.Person;
import Model.PersonLogs;
import Model.UserLogs;
import javax.swing.JSplitPane;

/**
 *
 * @author arpitabhagat
 */
public class PatientView extends javax.swing.JPanel {

    /**
     * Creates new form ViewPatient
     */
    PersonLogs personLogs;
    UserLogs userLogs;
    JSplitPane jSplitPane1;
    DoctorLogs doctorLogs;
    String userName;
    EncounterLogs encounterLogs;
    public PatientView(PersonLogs personLogs,UserLogs userLogs, JSplitPane jSplitPane1,String userName,DoctorLogs doctorLogs,EncounterLogs encounterLogs) {
        initComponents();
        this.personLogs = personLogs;
        this.userLogs = userLogs;
        this.jSplitPane1 = jSplitPane1;
        this.userName = userName;
        this.doctorLogs = doctorLogs;
        this.encounterLogs = encounterLogs;
//        Person personObject = null;
//        for (Person eh : personLogs.getPersonLogs()) {
//            if(eh.getUserName().equals(userName)){
//            personObject = eh;
//            }
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnViewVitals = new javax.swing.JButton();
        btnVisitDoctor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        btnViewVitals.setText("VIew Vitals");
        btnViewVitals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewVitalsActionPerformed(evt);
            }
        });

        btnVisitDoctor.setText("Visit a Doctor");
        btnVisitDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisitDoctorActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("VIEW PATIENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnViewVitals)
                        .addGap(36, 36, 36)
                        .addComponent(btnVisitDoctor)))
                .addContainerGap(408, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisitDoctor)
                    .addComponent(btnViewVitals))
                .addContainerGap(445, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisitDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisitDoctorActionPerformed
        // TODO add your handling code here:
        PatientVisitDoctor cP = new PatientVisitDoctor(personLogs,userLogs,jSplitPane1,userName,doctorLogs,encounterLogs);
        jSplitPane1.setRightComponent(cP);
    }//GEN-LAST:event_btnVisitDoctorActionPerformed

    private void btnViewVitalsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewVitalsActionPerformed
        // TODO add your handling code here:
//        PatientViewVitals pvv = new PatientViewVitals(personLogs,userLogs,jSplitPane1,userName,doctorLogs,encounterLogs);
//        jSplitPane1.setRightComponent(pvv);
    }//GEN-LAST:event_btnViewVitalsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewVitals;
    private javax.swing.JButton btnVisitDoctor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
